services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
